Description: pipeline to deploy cfn-service-catalog-portfolio-share
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "cfn-service-catalog-portfolio-share-ci-artifacts-${AWS::Region}"
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 365
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  CodeStarConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: service-catalog-portfolio-share
      ProviderType: GitHub
  CodeBuildBasePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CloudFormation
            Effect: Allow
            Action:
              - cloudformation:ValidateTemplate
            Resource:
              - "*"
          - Sid: CloudWatchLogs
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - "*"
          - Sid: IAM
            Effect: Allow
            Action:
              - sts:AssumeRole
              - iam:GetUser
              - iam:GetInstanceProfile
              - iam:PassRole
            Resource:
              - "*"
          - Sid: SSM
            Effect: Allow
            Action:
              - ssm:GetParameters
            Resource:
              - "*"
          - Sid: KMS
            Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource:
              - "*"
          - Sid: S3
            Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:DeleteObject
            Resource:
              - "*"
          - Sid: CodeBuild
            Effect: Allow
            Action:
              - codebuild:CreateReportGroup
              - codebuild:CreateReport
              - codebuild:UpdateReport
              - codebuild:BatchPutTestCases
              - codebuild:StartBuild
            Resource:
              - "*"
          - Sid: CodeStarConnections
            Effect: Allow
            Action:
              - codestar-connections:UseConnection
            Resource:
              - !GetAtt CodeStarConnection.ConnectionArn
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      ManagedPolicyArns:
        - !Ref CodeBuildBasePolicy
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
        Location: !Ref Bucket
        Path: /artifacts/cfn-service-catalog-portfolio-share/
        Packaging: NONE
        Name: build
        NamespaceType: BUILD_ID
      TimeoutInMinutes: 5
      Description: Builds cfn-service-catalog-portfolio-share
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-aarch64-standard:3.0
        Type: ARM_CONTAINER
        EnvironmentVariables:
          - Value: !Ref Bucket
            Name: ARTIFACTS_BUCKET
            Type: PLAINTEXT
      Name: cfn-service-catalog-portfolio-share
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
  CodePipelineBaseExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CloudFormation
            Effect: Allow
            Action:
              - cloudformation:*
            Resource:
              - "*"
          - Sid: IAM
            Effect: Allow
            Action:
              - iam:GetRole
              - iam:PassRole
            Resource:
              - "*"
          - Sid: CodeBuild
            Effect: Allow
            Action:
              - codebuild:StartBuild
              - codebuild:BatchGetBuilds
              - codebuild:StartBuildBatch
              - codebuild:BatchGetBuildBatches
            Resource:
              - "*"
          - Sid: KMS
            Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource:
              - "*"
          - Sid: S3
            Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:DeleteObject
            Resource:
              - "*"
          - Sid: CodeStarConnections
            Effect: Allow
            Action:
              - codestar-connections:UseConnection
            Resource:
              - !GetAtt CodeStarConnection.ConnectionArn
  CodePipelineBaseExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
      ManagedPolicyArns:
        - !Ref CodePipelineBaseExecutionPolicy
  CodePipelineCloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
      Policies:
        - PolicyName: codepipeline-cloudformation-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "*"
                Resource:
                  - "*"
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref Bucket
      Name: cfn-service-catalog-portfolio-share
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt CodePipelineBaseExecutionRole.Arn
      PipelineType: V2
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Version: "1"
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Clone-From-GitHub
              Namespace: SourceVariables
              Configuration:
                ConnectionArn: !Ref CodeStarConnection
                FullRepositoryId: AlexChesters/cfn-service-catalog-portfolio-share
                BranchName: main
                OutputArtifactFormat: CODE_ZIP
        - Name: Build
          Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: GitHubSource
              OutputArtifacts:
                - Name: BuiltSource
              RunOrder: 1
              Name: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
        - Name: Deploy
          Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuiltSource
              RunOrder: 1
              Name: Lambda
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: cfn-service-catalog-portfolio-share
                RoleArn: !GetAtt CodePipelineCloudFormationRole.Arn
                TemplatePath: BuiltSource::stacks/service-catalog-account/cfn-service-catalog-portfolio-share.yml
                TemplateConfiguration: BuiltSource::stacks/service-catalog-account/parameters.json
